In [1]:
import csv
import pandas as pd
import numpy as np
import glob
import matplotlib
import scipy as sp
from matplotlib import pyplot as plt
from itertools import cycle, islice

In [4]:
#load files
def load_file(path):
    sess = csv.reader(open(path))
    data = [row for row in sess]
    df = pd.DataFrame(np.array(data))
    df = df.T
    #df = df.apply(pd.to_numeric)
    df.head()
    return df

In [5]:
s01 = load_file('pupil_data/s01_pupil_diameter_3d.csv')

In [6]:
s01

,0,1,2,3,4,5,6,7,8,9,...,170452,170453,170454,170455,170456,170457,170458,170459,170460,170461
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,80434.17425007696,80434.17446177696,80434.17814547697,80434.18297677695,80434.19070497694,80434.2058436769,80434.21082297691,80434.22006017689,80434.22915837687,80434.23693977686,...,81870.36761436878,81870.39181626875,81870.39665526873,81870.40289356872,81870.41052626871,81870.4204567687,81870.42536396869,81870.43356446868,81870.44317366867,81870.45845916863